import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
    console.log('🌱 Seeding database...');

    // Clear existing data
    await prisma.scholarship.deleteMany();
    await prisma.universitySpecialization.deleteMany();
    await prisma.university.deleteMany();

    // Create Universities (MBA, MS, PhD programs)
    const universities = [
        // === MBA Programs ===
        {
            name: 'Harvard Business School',
            location: 'Boston',
            state: 'Massachusetts',
            country: 'USA',
            website: 'https://www.hbs.edu',
            overallRanking: 1,
            programRanking: 1,
            acceptanceRate: 0.11,
            avgGmat: 730,
            avgGpa: 3.71,
            avgWorkExpMonths: 60,
            programType: 'MBA',
            programDurationMonths: 24,
            classSize: 940,
            internationalPercent: 0.37,
            womenPercent: 0.43,
            tuitionAnnualUSD: 73440,
            totalCostAnnualUSD: 110740,
            avgFinancialAidUSD: 40000,
            needBlind: false,
            avgStartingSalaryUSD: 175000,
            avg10YearSalaryUSD: 350000,
            employmentRate: 0.95,
            topRecruiters: ['McKinsey', 'BCG', 'Bain', 'Goldman Sachs', 'Amazon'],
            studentToFaculty: 8.7,
            diversityScore: 85.0,
            campusType: 'Urban',
            successProbability: 92.0,
            studentSatisfaction: 88.0,
        },
        {
            name: 'Stanford Graduate School of Business',
            location: 'Stanford',
            state: 'California',
            country: 'USA',
            website: 'https://www.gsb.stanford.edu',
            overallRanking: 2,
            programRanking: 2,
            acceptanceRate: 0.06,
            avgGmat: 738,
            avgGpa: 3.75,
            avgWorkExpMonths: 54,
            programType: 'MBA',
            programDurationMonths: 24,
            classSize: 410,
            internationalPercent: 0.45,
            womenPercent: 0.42,
            tuitionAnnualUSD: 74706,
            totalCostAnnualUSD: 119000,
            avgFinancialAidUSD: 45000,
            needBlind: false,
            avgStartingSalaryUSD: 180000,
            avg10YearSalaryUSD: 380000,
            employmentRate: 0.96,
            topRecruiters: ['Google', 'Apple', 'McKinsey', 'Bain', 'Sequoia Capital'],
            studentToFaculty: 6.1,
            diversityScore: 90.0,
            campusType: 'Suburban',
            successProbability: 94.0,
            studentSatisfaction: 92.0,
        },
        {
            name: 'Wharton School - University of Pennsylvania',
            location: 'Philadelphia',
            state: 'Pennsylvania',
            country: 'USA',
            website: 'https://www.wharton.upenn.edu',
            overallRanking: 3,
            programRanking: 3,
            acceptanceRate: 0.19,
            avgGmat: 728,
            avgGpa: 3.60,
            avgWorkExpMonths: 60,
            programType: 'MBA',
            programDurationMonths: 24,
            classSize: 850,
            internationalPercent: 0.33,
            womenPercent: 0.40,
            tuitionAnnualUSD: 81378,
            totalCostAnnualUSD: 118870,
            avgFinancialAidUSD: 35000,
            needBlind: false,
            avgStartingSalaryUSD: 165000,
            avg10YearSalaryUSD: 340000,
            employmentRate: 0.94,
            topRecruiters: ['Goldman Sachs', 'JP Morgan', 'McKinsey', 'BCG', 'Amazon'],
            studentToFaculty: 7.2,
            diversityScore: 82.0,
            campusType: 'Urban',
            successProbability: 90.0,
            studentSatisfaction: 85.0,
        },
        {
            name: 'MIT Sloan School of Management',
            location: 'Cambridge',
            state: 'Massachusetts',
            country: 'USA',
            website: 'https://mitsloan.mit.edu',
            overallRanking: 4,
            programRanking: 4,
            acceptanceRate: 0.14,
            avgGmat: 728,
            avgGpa: 3.65,
            avgWorkExpMonths: 60,
            programType: 'MBA',
            programDurationMonths: 24,
            classSize: 410,
            internationalPercent: 0.42,
            womenPercent: 0.41,
            tuitionAnnualUSD: 77168,
            totalCostAnnualUSD: 115000,
            avgFinancialAidUSD: 38000,
            needBlind: false,
            avgStartingSalaryUSD: 170000,
            avg10YearSalaryUSD: 360000,
            employmentRate: 0.95,
            topRecruiters: ['Amazon', 'Google', 'McKinsey', 'BCG', 'Apple'],
            studentToFaculty: 9.0,
            diversityScore: 88.0,
            campusType: 'Urban',
            successProbability: 91.0,
            studentSatisfaction: 89.0,
        },
        {
            name: 'Columbia Business School',
            location: 'New York',
            state: 'New York',
            country: 'USA',
            website: 'https://www8.gsb.columbia.edu',
            overallRanking: 5,
            programRanking: 5,
            acceptanceRate: 0.16,
            avgGmat: 726,
            avgGpa: 3.60,
            avgWorkExpMonths: 60,
            programType: 'MBA',
            programDurationMonths: 24,
            classSize: 750,
            internationalPercent: 0.45,
            womenPercent: 0.41,
            tuitionAnnualUSD: 77376,
            totalCostAnnualUSD: 120000,
            avgFinancialAidUSD: 32000,
            needBlind: false,
            avgStartingSalaryUSD: 165000,
            avg10YearSalaryUSD: 350000,
            employmentRate: 0.93,
            topRecruiters: ['Goldman Sachs', 'JP Morgan', 'McKinsey', 'Google', 'Amazon'],
            studentToFaculty: 8.5,
            diversityScore: 86.0,
            campusType: 'Urban',
            successProbability: 89.0,
            studentSatisfaction: 84.0,
        },
        {
            name: 'University of Chicago Booth School of Business',
            location: 'Chicago',
            state: 'Illinois',
            country: 'USA',
            website: 'https://www.chicagobooth.edu',
            overallRanking: 6,
            programRanking: 6,
            acceptanceRate: 0.23,
            avgGmat: 730,
            avgGpa: 3.61,
            avgWorkExpMonths: 60,
            programType: 'MBA',
            programDurationMonths: 24,
            classSize: 590,
            internationalPercent: 0.36,
            womenPercent: 0.39,
            tuitionAnnualUSD: 74919,
            totalCostAnnualUSD: 115000,
            avgFinancialAidUSD: 30000,
            needBlind: false,
            avgStartingSalaryUSD: 168000,
            avg10YearSalaryUSD: 345000,
            employmentRate: 0.94,
            topRecruiters: ['McKinsey', 'BCG', 'Bain', 'Amazon', 'Deloitte'],
            studentToFaculty: 7.8,
            diversityScore: 83.0,
            campusType: 'Urban',
            successProbability: 88.0,
            studentSatisfaction: 86.0,
        },
        {
            name: 'Northwestern Kellogg School of Management',
            location: 'Evanston',
            state: 'Illinois',
            country: 'USA',
            website: 'https://www.kellogg.northwestern.edu',
            overallRanking: 7,
            programRanking: 7,
            acceptanceRate: 0.20,
            avgGmat: 727,
            avgGpa: 3.60,
            avgWorkExpMonths: 60,
            programType: 'MBA',
            programDurationMonths: 24,
            classSize: 480,
            internationalPercent: 0.32,
            womenPercent: 0.44,
            tuitionAnnualUSD: 76536,
            totalCostAnnualUSD: 117000,
            avgFinancialAidUSD: 33000,
            needBlind: false,
            avgStartingSalaryUSD: 165000,
            avg10YearSalaryUSD: 340000,
            employmentRate: 0.93,
            topRecruiters: ['Amazon', 'McKinsey', 'BCG', 'Google', 'Microsoft'],
            studentToFaculty: 8.2,
            diversityScore: 87.0,
            campusType: 'Suburban',
            successProbability: 87.0,
            studentSatisfaction: 85.0,
        },

        // === MS Programs (Computer Science) ===
        {
            name: 'Carnegie Mellon University',
            location: 'Pittsburgh',
            state: 'Pennsylvania',
            country: 'USA',
            website: 'https://www.cs.cmu.edu',
            overallRanking: 1,
            programRanking: 1,
            acceptanceRate: 0.08,
            avgGreVerbal: 162,
            avgGreQuant: 168,
            avgGpa: 3.85,
            avgWorkExpMonths: 12,
            programType: 'MS',
            programDurationMonths: 18,
            classSize: 200,
            internationalPercent: 0.65,
            womenPercent: 0.28,
            tuitionAnnualUSD: 52000,
            totalCostAnnualUSD: 78000,
            avgFinancialAidUSD: 15000,
            needBlind: false,
            avgStartingSalaryUSD: 155000,
            avg10YearSalaryUSD: 280000,
            employmentRate: 0.98,
            topRecruiters: ['Google', 'Meta', 'Amazon', 'Microsoft', 'Apple'],
            studentToFaculty: 5.5,
            diversityScore: 75.0,
            campusType: 'Urban',
            successProbability: 95.0,
            studentSatisfaction: 90.0,
        },
        {
            name: 'Stanford University',
            location: 'Stanford',
            state: 'California',
            country: 'USA',
            website: 'https://cs.stanford.edu',
            overallRanking: 2,
            programRanking: 2,
            acceptanceRate: 0.05,
            avgGreVerbal: 163,
            avgGreQuant: 169,
            avgGpa: 3.90,
            avgWorkExpMonths: 6,
            programType: 'MS',
            programDurationMonths: 18,
            classSize: 120,
            internationalPercent: 0.55,
            womenPercent: 0.32,
            tuitionAnnualUSD: 58416,
            totalCostAnnualUSD: 95000,
            avgFinancialAidUSD: 20000,
            needBlind: true,
            avgStartingSalaryUSD: 165000,
            avg10YearSalaryUSD: 310000,
            employmentRate: 0.99,
            topRecruiters: ['Google', 'Apple', 'Meta', 'Tesla', 'Nvidia'],
            studentToFaculty: 4.8,
            diversityScore: 82.0,
            campusType: 'Suburban',
            successProbability: 96.0,
            studentSatisfaction: 93.0,
        },
        {
            name: 'Massachusetts Institute of Technology',
            location: 'Cambridge',
            state: 'Massachusetts',
            country: 'USA',
            website: 'https://www.eecs.mit.edu',
            overallRanking: 3,
            programRanking: 3,
            acceptanceRate: 0.07,
            avgGreVerbal: 162,
            avgGreQuant: 169,
            avgGpa: 3.88,
            avgWorkExpMonths: 8,
            programType: 'MS',
            programDurationMonths: 18,
            classSize: 150,
            internationalPercent: 0.60,
            womenPercent: 0.30,
            tuitionAnnualUSD: 57590,
            totalCostAnnualUSD: 85000,
            avgFinancialAidUSD: 18000,
            needBlind: true,
            avgStartingSalaryUSD: 160000,
            avg10YearSalaryUSD: 300000,
            employmentRate: 0.98,
            topRecruiters: ['Google', 'Amazon', 'Microsoft', 'Apple', 'Meta'],
            studentToFaculty: 5.2,
            diversityScore: 80.0,
            campusType: 'Urban',
            successProbability: 95.0,
            studentSatisfaction: 91.0,
        },
        {
            name: 'University of California Berkeley',
            location: 'Berkeley',
            state: 'California',
            country: 'USA',
            website: 'https://eecs.berkeley.edu',
            overallRanking: 4,
            programRanking: 4,
            acceptanceRate: 0.10,
            avgGreVerbal: 160,
            avgGreQuant: 168,
            avgGpa: 3.80,
            avgWorkExpMonths: 10,
            programType: 'MS',
            programDurationMonths: 18,
            classSize: 180,
            internationalPercent: 0.58,
            womenPercent: 0.29,
            tuitionAnnualUSD: 29754,
            totalCostAnnualUSD: 65000,
            avgFinancialAidUSD: 12000,
            needBlind: false,
            avgStartingSalaryUSD: 150000,
            avg10YearSalaryUSD: 275000,
            employmentRate: 0.97,
            topRecruiters: ['Google', 'Meta', 'Apple', 'Tesla', 'Uber'],
            studentToFaculty: 6.0,
            diversityScore: 85.0,
            campusType: 'Urban',
            successProbability: 93.0,
            studentSatisfaction: 88.0,
        },
        {
            name: 'University of Illinois Urbana-Champaign',
            location: 'Urbana',
            state: 'Illinois',
            country: 'USA',
            website: 'https://cs.illinois.edu',
            overallRanking: 5,
            programRanking: 5,
            acceptanceRate: 0.15,
            avgGreVerbal: 158,
            avgGreQuant: 167,
            avgGpa: 3.75,
            avgWorkExpMonths: 12,
            programType: 'MS',
            programDurationMonths: 18,
            classSize: 220,
            internationalPercent: 0.70,
            womenPercent: 0.27,
            tuitionAnnualUSD: 34330,
            totalCostAnnualUSD: 58000,
            avgFinancialAidUSD: 10000,
            needBlind: false,
            avgStartingSalaryUSD: 140000,
            avg10YearSalaryUSD: 260000,
            employmentRate: 0.96,
            topRecruiters: ['Amazon', 'Microsoft', 'Google', 'Meta', 'IBM'],
            studentToFaculty: 7.0,
            diversityScore: 78.0,
            campusType: 'Suburban',
            successProbability: 91.0,
            studentSatisfaction: 86.0,
        },

        // === PhD Programs ===
        {
            name: 'Harvard University',
            location: 'Cambridge',
            state: 'Massachusetts',
            country: 'USA',
            website: 'https://gsas.harvard.edu',
            overallRanking: 1,
            programRanking: 1,
            acceptanceRate: 0.03,
            avgGreVerbal: 165,
            avgGreQuant: 168,
            avgGpa: 3.92,
            avgWorkExpMonths: 0,
            programType: 'PhD',
            programDurationMonths: 60,
            classSize: 50,
            internationalPercent: 0.40,
            womenPercent: 0.45,
            tuitionAnnualUSD: 0,
            totalCostAnnualUSD: 0,
            avgFinancialAidUSD: 45000,
            needBlind: true,
            avgStartingSalaryUSD: 120000,
            avg10YearSalaryUSD: 180000,
            employmentRate: 0.95,
            topRecruiters: ['Academia', 'Google Research', 'Microsoft Research', 'Meta AI', 'OpenAI'],
            studentToFaculty: 3.5,
            diversityScore: 88.0,
            campusType: 'Urban',
            successProbability: 97.0,
            studentSatisfaction: 92.0,
        },
        {
            name: 'Princeton University',
            location: 'Princeton',
            state: 'New Jersey',
            country: 'USA',
            website: 'https://www.princeton.edu',
            overallRanking: 2,
            programRanking: 2,
            acceptanceRate: 0.04,
            avgGreVerbal: 164,
            avgGreQuant: 169,
            avgGpa: 3.90,
            avgWorkExpMonths: 0,
            programType: 'PhD',
            programDurationMonths: 60,
            classSize: 45,
            internationalPercent: 0.38,
            womenPercent: 0.42,
            tuitionAnnualUSD: 0,
            totalCostAnnualUSD: 0,
            avgFinancialAidUSD: 42000,
            needBlind: true,
            avgStartingSalaryUSD: 115000,
            avg10YearSalaryUSD: 175000,
            employmentRate: 0.94,
            topRecruiters: ['Academia', 'Google Research', 'IBM Research', 'DeepMind', 'Amazon Science'],
            studentToFaculty: 3.2,
            diversityScore: 85.0,
            campusType: 'Suburban',
            successProbability: 96.0,
            studentSatisfaction: 91.0,
        },
        {
            name: 'Yale University',
            location: 'New Haven',
            state: 'Connecticut',
            country: 'USA',
            website: 'https://gsas.yale.edu',
            overallRanking: 3,
            programRanking: 3,
            acceptanceRate: 0.05,
            avgGreVerbal: 163,
            avgGreQuant: 167,
            avgGpa: 3.88,
            avgWorkExpMonths: 0,
            programType: 'PhD',
            programDurationMonths: 60,
            classSize: 55,
            internationalPercent: 0.35,
            womenPercent: 0.48,
            tuitionAnnualUSD: 0,
            totalCostAnnualUSD: 0,
            avgFinancialAidUSD: 40000,
            needBlind: true,
            avgStartingSalaryUSD: 110000,
            avg10YearSalaryUSD: 170000,
            employmentRate: 0.93,
            topRecruiters: ['Academia', 'Research Institutes', 'Google', 'Microsoft', 'Meta'],
            studentToFaculty: 3.8,
            diversityScore: 87.0,
            campusType: 'Urban',
            successProbability: 95.0,
            studentSatisfaction: 90.0,
        },
    ];

    for (const uni of universities) {
        const university = await prisma.university.create({
            data: uni,
        });

        // Add specializations based on program type
        let specializations: { universityId: string; specialization: string; ranking: number }[] = [];

        if (uni.programType === 'MBA') {
            specializations = [
                { universityId: university.id, specialization: 'Finance', ranking: 1 },
                { universityId: university.id, specialization: 'Entrepreneurship', ranking: 2 },
                { universityId: university.id, specialization: 'Strategy', ranking: 1 },
                { universityId: university.id, specialization: 'Marketing', ranking: 3 },
            ];
        } else if (uni.programType === 'MS') {
            specializations = [
                { universityId: university.id, specialization: 'Artificial Intelligence', ranking: 1 },
                { universityId: university.id, specialization: 'Machine Learning', ranking: 1 },
                { universityId: university.id, specialization: 'Software Engineering', ranking: 2 },
                { universityId: university.id, specialization: 'Data Science', ranking: 2 },
            ];
        } else if (uni.programType === 'PhD') {
            specializations = [
                { universityId: university.id, specialization: 'Computer Science', ranking: 1 },
                { universityId: university.id, specialization: 'Applied Mathematics', ranking: 2 },
                { universityId: university.id, specialization: 'Economics', ranking: 3 },
            ];
        }

        await prisma.universitySpecialization.createMany({
            data: specializations,
        });

        // Add scholarships
        await prisma.scholarship.createMany({
            data: [
                {
                    universityId: university.id,
                    name: 'Merit Scholarship',
                    provider: university.name,
                    amountUSD: 50000,
                    type: 'Merit',
                    description: 'Awarded to students with exceptional academic records',
                    eligibility: 'GPA > 3.7, GMAT > 720',
                    requirements: ['Application essay', 'Transcripts'],
                    minGpa: 3.7,
                    minGmat: 720,
                    deadline: new Date('2026-01-15'),
                    renewable: true,
                    applicationDifficulty: 7,
                    successRate: 0.15,
                },
                {
                    universityId: university.id,
                    name: 'Diversity Fellowship',
                    provider: university.name,
                    amountUSD: 30000,
                    type: 'Diversity',
                    description: 'Supporting underrepresented students',
                    eligibility: 'Underrepresented background',
                    requirements: ['Diversity statement', 'Application'],
                    minGpa: 3.3,
                    targetDemographic: 'Underrepresented minorities',
                    deadline: new Date('2026-02-01'),
                    renewable: false,
                    applicationDifficulty: 5,
                    successRate: 0.25,
                },
            ],
        });

        console.log(`✅ Created ${university.name}`);
    }

    console.log('🎉 Seeding completed!');
}

main()
    .catch((e) => {
        console.error('❌ Seeding failed:', e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
